services:
  db-event-catalog:
    container_name: event-catalog-postgres
    image: postgres:latest
    restart: always
    user: postgres
    env_file:
      - env/.env-event-catalog-db
    volumes:
      - postgres_data_event_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - event-catalog-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 64M
networks:
  event-catalog-network:
    driver: bridge
volumes:
  postgres_data_event_db: